name: Node.js CI


on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  build:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: ./server
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
        cache-dependency-path: '**/pnpm-lock.yaml'
    - run: pm2 stop prod
    - run: pnpm install
    - run: pnpm build
    - run: pnpm start & npx wait-on http://localhost:3000
    - run: cd .. 
    - run: pm2 start pnpm --name "byderm-cupones" --start
    - run: pm2 save
    - run: sudo service nginx restart

  